### ISSUE TITLE
At startup using pm2 on Ubuntu 16.04

### ISSUE THREAD

**Issue by anonuserperson** [bennettca/ProfitTrailer-new-binance-listings#13]
[PM2][ERROR] Error while launching application Error: spawn EACCES
    at exports._errnoException (util.js:870:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at /usr/local/lib/node_modules/pm2/lib/God/ForkMode.js:94:20
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:5315:29)
    at /usr/local/lib/node_modules/pm2/node_modules/async/dist/async.js:958:16
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Utility.js:172:13)
    at emitOne (events.js:77:13)
    at WriteStream.emit (events.js:169:7)

**Comment by Darent74** [comment]
tested on Ubuntu 16.04  , try my json file

Extract json file from zip
Add to your Feeder directory where blacklist files located  

start with command 
   pm2 start  pm2-PT-Blacklist.json

[pm2-PT-Blacklist..zip](https://github.com/bennettca/binance-auto-blacklist/files/1780949/pm2-PT-Blacklist.zip)

**Comment by Salocin90** [comment]
Worked like a charm! Thanks @Darent74
